### ISSUE TITLE
Select most representative images of interesting doses

### ISSUE THREAD

**Issue by gwaygenomics** [broadinstitute/2018_05_30_ResistanceMechanisms_Kapoor#3]
Related to #2

**Comment by gwaygenomics** [comment]
Chatted with @bethac07 about selecting images. Beth walked me through inputting 5 channels into fiji. We selected two images:

| Well | Clone | Dose | Batch |
| :---: | :----: | :----: | :-----: | 
| C09 | E | 0.7 | 2 |
| D09 | E | 7 | 2 |

**Comment by gwaygenomics** [comment]
It is not clear if the pictures themselves can live in this public repo (yet)

**Comment by bethac07** [comment]
More specifically, we selected C09 s1, and D09 s2. (Why those? Cuz. That's why).
